In [1]:
pip install pandas sqlalchemy psycopg2

Requirement already satisfied: pandas in C:\Users\lohit\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (3.0.1)
Collecting sqlalchemy
  Downloading sqlalchemy-2.0.48-cp314-cp314-win_amd64.whl.metadata (9.8 kB)
Collecting psycopg2
  Downloading psycopg2-2.9.11-cp314-cp314-win_amd64.whl.metadata (5.1 kB)
Requirement already satisfied: numpy>=2.3.3 in C:\Users\lohit\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from pandas) (2.4.2)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\lohit\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\lohit\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from pandas) (2025.3)
Collecting greenlet>=1 (from sqlalchemy)
  Downloading greenlet-3.3.2-cp314-cp314-win_amd64.whl.metadata (3.8 kB)
Requirement already satisfied: typing-extensions>=4.6.0 in C:\Users\lohit\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from sqlalchemy) (4.15.0)
Requirement already satisfied: six>=1.5 in C:\Users\lohit\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading sqlalchemy-2.0.48-cp314-cp314-win_amd64.whl (2.1 MB)
   ---------------------------------------- 0.0/2.1 MB ? eta -:--:--
   ------------------- -------------------- 1.0/2.1 MB 5.3 MB/s eta 0:00:01
   ---------------------------------------  2.1/2.1 MB 5.3 MB/s eta 0:00:01
   ---------------------------------------- 2.1/2.1 MB 4.8 MB/s  0:00:00
Downloading psycopg2-2.9.11-cp314-cp314-win_amd64.whl (2.8 MB)
   ---------------------------------------- 0.0/2.8 MB ? eta -:--:--
   -------------- ------------------------- 1.0/2.8 MB 5.3 MB/s eta 0:00:01
   ----------------------------- ---------- 2.1/2.8 MB 5.1 MB/s eta 0:00:01
   ---------------------------------------- 2.8/2.8 MB 4.6 MB/s  0:00:00
Downloading greenlet-3.3.2-cp314-cp314-win_amd64.whl (232 kB)
Installing collected packages: psycopg2, greenlet, sqlalchemy

   ---------------------------------------- 0/3 [psycopg2]
   ---------------------------------------- 0/3 [psycopg2]
   ---------------------------------------- 0/3 [psycopg2]
   ---------------------------------------- 0/3 [psycopg2]
   ---------------------------------------- 0/3 [psycopg2]
   ------------- -------------------------- 1/3 [greenlet]
   ------------- -------------------------- 1/3 [greenlet]
   ------------- -------------------------- 1/3 [greenlet]
   ------------- -------------------------- 1/3 [greenlet]
   ------------- -------------------------- 1/3 [greenlet]
   ------------- -------------------------- 1/3 [greenlet]
   ------------- -------------------------- 1/3 [greenlet]
   ------------- -------------------------- 1/3 [greenlet]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   ---------------------------------------- 3/3 [sqlalchemy]

Successfully installed greenlet-3.3.2 psycopg2-2.9.11 sqlalchemy-2.0.48
Note: you may need to restart the kernel to use updated packages.

In [5]:
from sqlalchemy import create_engine
import urllib.parse

password = urllib.parse.quote_plus("akhil@143")

engine = create_engine(
    f"postgresql+psycopg2://postgres:{password}@localhost:5432/ecommerce_analytics"
)

In [6]:
customers = pd.read_csv("../data/olist_customers_dataset.csv")
orders = pd.read_csv("../data/olist_orders_dataset.csv")
payments = pd.read_csv("../data/olist_order_payments_dataset.csv")

In [7]:
customers = customers[['customer_id','customer_city','customer_state']]
orders = orders[['order_id','customer_id','order_purchase_timestamp','order_status']]
payments = payments[['order_id','payment_value']]

In [8]:
customers.to_sql("customers", engine, if_exists='append', index=False)
orders.to_sql("orders", engine, if_exists='append', index=False)
payments.to_sql("payments", engine, if_exists='append', index=False)

886

In [10]:
import pandas as pd

df = pd.read_csv("../data/customer_last_purchase.csv")

df.head()

                        customer_id        last_purchase
0  09033cfedb9bab5c54a33f339fd94ad0  2018-08-07 20:21:41
1  9f184cd2aa748ce963a8d5e075aff28e  2017-07-15 11:29:35
2  1e11025f8a103ddbf95ddaca105f7f4a  2018-03-15 15:20:17
3  f796cc9e19019673220efa160fe7e610  2017-01-22 11:08:52
4  c1d5e6bc6c7bd0a017a08818dcde3295  2017-08-05 21:43:29

In [11]:
df['last_purchase'] = pd.to_datetime(df['last_purchase'])

cutoff = df['last_purchase'].max() - pd.Timedelta(days=180)

df['churn'] = df['last_purchase'] < cutoff

churn_rate = df['churn'].mean()

print("Churn Rate:", churn_rate)

Churn Rate: 0.7165756579278165

In [12]:
orders = pd.read_sql("SELECT * FROM orders", engine)
payments = pd.read_sql("SELECT * FROM payments", engine)

data = orders.merge(payments, on="order_id")

In [20]:
clv_df = data.groupby("customer_id").agg({
    "payment_value":"sum",
    "order_id":"count"
})

In [21]:
clv_df["segment"] = pd.qcut(
    clv_df["payment_value"],
    q=3,
    labels=["Low","Medium","High"]
)

In [22]:
from sklearn.linear_model import LinearRegression
import numpy as np

monthly_rev = data.groupby(
    pd.to_datetime(data['order_purchase_timestamp']).dt.to_period('M')
)['payment_value'].sum().reset_index()

X = np.arange(len(monthly_rev)).reshape(-1,1)
y = monthly_rev['payment_value']

model = LinearRegression()
model.fit(X,y)

future = model.predict([[len(monthly_rev)]])
print(future)

[1044589.1195]

In [16]:
clv_df.head()

                                  payment_value  order_id segment
customer_id
00012a2ce6f8dcda20d059ce98491703         114.74         1  Medium
000161a058600d5901f007fab4c27140          67.41         1     Low
0001fd6190edaaf884bcaf3d49edf079         195.42         1    High
0002414f95344307404f0ace7a26f1d5         179.35         1    High
000379cdec625522490c315e70c7a9fb         107.01         1  Medium

In [17]:
clv_df = clv_df.reset_index()

In [18]:
clv_df.to_csv("../data/clv_segment.csv", index=False)